#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  7 14:32:01 2020

@author: f4him
"""
import math

num, pos = map(int,input().split())

if pos<=math.ceil(num/2):
    print(pos*2-1)
else:
    if num%2==1:
        print(2*pos-num-1)
    else:
        print(2*pos-num)